#!/usr/bin/env bash
set -e

if [[ -z "$1" ]] ; then
  error "You need to finish one task"
  exit 1
fi

list=$(awk 'NF{print}' "$T_FILE")
if [[ "$1" -gt $(echo "$list" | wc -l) ]] ; then
  echo "No such task $1" >&2
  exit 1
fi
task=$(echo "$list" | awk "NF{if(++a == $1) print \$0}")
echo "$list" | awk "NF{if (++a != $1) print \$0}" > "$T_FILE"

echo "Finished task $1!" >&1
echo $task
